(function(){
'use strict';
const C=window.PONTO_CORE,$=id=>document.getElementById(id),sb=window.SISLOT_SB;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const br=d=>d?d.slice(0,10).split('-').reverse().join('/'):'—';
const today=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'America/Sao_Paulo'}).format(new Date());
const month=d=>d.slice(0,7)+'-01';
let ctx,staff=[],events=[],punches=[],imports=[],days=[],pending,loaded=false,busy=false;
const loja=()=>Number($('loja').value),user=()=>Number($('funcionario').value);
const person=()=>staff.find(s=>Number(s.id)===user());
function message(t,error=false){$('status').textContent=t;$('status').classList.toggle('error',error);}
async function run(fn){if(busy)return;busy=true;document.querySelector('main').setAttribute('aria-busy','true');document.body.classList.add('is-loading');document.querySelectorAll('button').forEach(b=>b.dataset.wasDisabled=b.disabled?'1':'0');document.querySelectorAll('button').forEach(b=>b.disabled=true);try{await fn();}catch(e){console.error(e);message(e.message||String(e),true);}finally{document.querySelectorAll('button').forEach(b=>b.disabled=b.dataset.wasDisabled==='1');busy=false;document.querySelector('main').setAttribute('aria-busy','false');document.body.classList.remove('is-loading');updateSelection();}}
async function query(q){const r=await q;if(r.error)throw Error(r.error.message);return r.data;}
async function all(table,configure){let result=[];for(let from=0;;from+=1000){const r=await query(configure(sb.from(table).select('*')).order('id').range(from,from+999));result.push(...r);if(r.length<1000)break;}return result;}
function base(type,date,reason,extra={}){return {loteria_id:loja(),usuario_id:user()||null,tipo:type,data_referencia:date,competencia:month(date),motivo:reason,...extra};}
async function save(items){await query(sb.rpc('ponto_lancar_lote',{p_eventos:items}));}
function rule(date){return C.latest(events,'JORNADA',date,user())?.dados||C.schedule(loja());}
function holiday(date){return events.filter(e=>e.tipo==='FERIADO'&&e.data_referencia===date).sort((a,b)=>a.criado_em.localeCompare(b.criado_em)).at(-1);}
function activeBank(date){return events.find(e=>e.tipo==='BANCO'&&e.usuario_id===user()&&e.data_referencia===date&&!events.some(r=>r.estorno_de===e.id));}
function buildDays(){return C.dates($('inicio').value,$('fim').value).map(date=>{
 const raw=punches.filter(p=>{if(p.instante.slice(0,10)!==date)return false;const map=events.filter(e=>e.tipo==='VINCULO'&&e.dados.dispositivo===p.dispositivo&&e.dados.codigo===p.codigo&&e.data_referencia<=date).sort((a,b)=>a.data_referencia.localeCompare(b.data_referencia)||a.criado_em.localeCompare(b.criado_em)).at(-1);return Number(map?.usuario_id)===user();}).sort((a,b)=>a.instante.localeCompare(b.instante));
 const changes=events.filter(e=>['AJUSTE','RESTAURAR'].includes(e.tipo)&&Number(e.usuario_id)===user()&&e.data_referencia===date).sort((a,b)=>a.criado_em.localeCompare(b.criado_em)||a.id.localeCompare(b.id));
 const adj=changes.at(-1)?.tipo==='AJUSTE'?changes.at(-1):null;
 const h=holiday(date);let times=adj?.dados.horarios??raw.map(p=>p.instante.slice(11,16));const kind=adj?.dados.situacao||(h?.dados.ativo!==false&&h?'FERIADO':'NORMAL');
 const r=C.evaluate(date,times,rule(date),kind);return {date,raw,times,kind,adjusted:!!adj,reason:adj?.motivo||h?.dados.nome||'',...r,bank:activeBank(date)};
 });}
const metric=(label,value)=>`<div class="metric">${esc(label)}<strong>${esc(value)}</strong></div>`;
function updateSelection(){
 const boxes=[...document.querySelectorAll('.diaCheck:not(:disabled)')];
 const selected=boxes.filter(c=>c.checked).map(c=>days.find(d=>d.date===c.value));
 const credit=selected.reduce((n,d)=>n+Math.max(0,d.delta),0),debit=selected.reduce((n,d)=>n+Math.min(0,d.delta),0);
 $('selecao').textContent=selected.length?`${selected.length} dia(s) · Créditos ${C.hm(credit)} · Débitos ${C.hm(debit)} · Líquido ${C.hm(credit+debit)}`:'Selecione os dias que deseja enviar ao banco';
 if(!busy)$('enviar').disabled=!loaded||!selected.length;
 const visible=boxes.filter(c=>!c.closest('tr').hidden);
 $('todos').checked=!!visible.length&&visible.every(c=>c.checked);
 $('todos').indeterminate=visible.some(c=>c.checked)&&!$('todos').checked;
}
function filterDays(){
 const filter=$('filtroDias').value;
 document.querySelectorAll('#dias tr[data-date]').forEach(row=>{const d=days.find(d=>d.date===row.dataset.date);row.hidden=!(filter==='todos'||filter==='pendentes'&&d.delta===null||filter==='disponiveis'&&d.delta!==null&&!!d.delta&&!d.bank||filter==='ajustados'&&d.adjusted||filter==='banco'&&!!d.bank);});
 updateSelection();
}
async function selectMonth(offset,current=false){
 const anchor=current?today():$('inicio').value;
 const date=new Date(anchor+'T12:00:00Z');date.setUTCDate(1);date.setUTCMonth(date.getUTCMonth()+offset);
 $('inicio').value=date.toISOString().slice(0,10);date.setUTCMonth(date.getUTCMonth()+1);date.setUTCDate(0);
 $('fim').value=current?today():date.toISOString().slice(0,10);await load();
}
function render(){if(!user()){$('contexto').textContent='Selecione um funcionário para iniciar a conferência.';$('selecao').textContent='Nenhum dia selecionado';$('enviar').disabled=true;$('totais').innerHTML='';$('saldos').innerHTML='';$('extrato').innerHTML='';$('dias').innerHTML='<tr><td colspan="8" class="empty">Selecione um funcionário.</td></tr>';return;}days=buildDays();
 $('contexto').textContent=`${person()?.nome||'Funcionário'} · ${br($('inicio').value)} a ${br($('fim').value)}`;
 const pendingDays=days.filter(d=>d.delta===null).length;
 $('totais').innerHTML=metric('Trabalhadas reais',C.hm(days.reduce((s,d)=>s+(d.worked||0),0)))+metric('Diferença apurada',C.hm(days.reduce((s,d)=>s+(d.delta||0),0)))+metric('Dias pendentes',pendingDays)+metric('Saldo geral atual',C.hm(C.balance(employeeEvents(),today())));
 $('dias').innerHTML=days.map(d=>`<tr data-date="${d.date}" class="${d.delta===null?'pending-row':d.bank?'bank-row':''}"><td><input type="checkbox" class="diaCheck" value="${d.date}" ${d.delta===null||!d.delta||d.bank?'disabled':''} aria-label="Selecionar ${br(d.date)}"></td><td>${br(d.date)} ${['DOM','SEG','TER','QUA','QUI','SEX','SÁB'][C.weekday(d.date)]}</td><td>${esc(d.times.join(' · ')||d.kind)} ${d.adjusted?'<span class="badge">Ajustado</span>':''}</td><td>${d.worked===null?'—':C.hm(d.worked)}</td><td>${C.hm(d.expected)}</td><td class="${d.delta>0?'positive':d.delta<0?'negative':''}">${d.delta===null?'—':C.hm(d.delta)}</td><td class="${d.delta===null?'warning':''}" title="${esc(d.reason)}">${esc(d.bank?'No banco':d.status.replaceAll('_',' '))}</td><td><button class="small secondary" data-edit="${d.date}">Tratar</button> <button class="small secondary" data-original="${d.date}">Original</button></td></tr>`).join('');
 renderBank();renderConfig();filterDays();
}
function employeeEvents(){return events.filter(e=>Number(e.usuario_id)===user());}
function renderBank(){const ev=employeeEvents();const before=new Date($('inicio').value+'T12:00:00Z');before.setUTCDate(before.getUTCDate()-1);const previous=C.balance(ev,before.toISOString().slice(0,10));const end=C.balance(ev,$('fim').value);
 $('saldos').innerHTML=metric('Saldo anterior',C.hm(previous))+metric('Movimento líquido do período',C.hm(end-previous))+metric('Saldo no fim do período',C.hm(end))+metric('Saldo geral atual',C.hm(C.balance(ev,today())));
 const bank=ev.filter(e=>['BANCO','PAGAMENTO','ESTORNO'].includes(e.tipo)).sort((a,b)=>a.data_referencia.localeCompare(b.data_referencia)||a.criado_em.localeCompare(b.criado_em)||a.id.localeCompare(b.id));let balance=0;const rows=[];
 for(const e of bank){balance+=e.minutos;if(e.data_referencia<$('inicio').value||e.data_referencia>$('fim').value)continue;const reversed=ev.some(r=>r.estorno_de===e.id);if(!$('liquidados').checked&&(reversed||e.tipo==='ESTORNO'))continue;
 rows.push(`<tr><td>${br(e.data_referencia)}</td><td>${esc(e.competencia.slice(0,7).split('-').reverse().join('/'))}</td><td>${esc(e.tipo)} ${reversed?'(estornado)':''}</td><td class="${e.minutos>0?'positive':'negative'}">${C.hm(e.minutos)}</td><td>${C.hm(balance)}</td><td>${esc(e.motivo)}<br><small class="muted">Registrado: ${new Date(e.criado_em).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</small></td><td>${!reversed&&e.tipo!=='ESTORNO'?`<button class="small secondary" data-reverse="${e.id}">Estornar</button>`:'—'}</td></tr>`);}
 $('extrato').innerHTML=rows.join('')||'<tr><td colspan="7" class="empty">Sem movimentos no período.</td></tr>';
}
function renderConfig(){const r=rule($('inicio').value);$('jornadaAtual').textContent=r?`Jornada em ${br($('inicio').value)}: ${r.weekday.join(' / ')} · Sábado: ${r.saturday.join(' / ')}.`:'Cadastre a jornada individual desta loja antes de apurar.';
 let suggested=C.standard;
 if(!r&&loja()===3){const name=(person()?.nome||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();if(name.startsWith('flavia'))suggested={...C.standard,weekday:['07:00','11:00','12:00','16:00']};else if(name.startsWith('leandro'))suggested={...C.standard,weekday:['10:00','13:00','14:00','19:00']};}
 const v=r||suggested;['j1','j2','j3','j4'].forEach((id,i)=>$(id).value=v.weekday[i]);$('s1').value=v.saturday[0];$('s2').value=v.saturday[1];$('atraso').value=v.late;$('he').value=v.extra;$('antecipada').value=v.early;$('intervalo').value=v.interval;$('limiar').value=v.threshold;$('percentual').value=v.extraPercent;
 const dates=[...new Set(events.filter(e=>e.tipo==='FERIADO').map(e=>e.data_referencia))].sort();$('feriados').innerHTML=dates.map(d=>holiday(d)).filter(e=>e.dados.ativo!==false).map(e=>`<div class="linkrow">${br(e.data_referencia)} — ${esc(e.dados.nome)} <button class="small secondary" data-holiday="${e.id}">Desativar</button></div>`).join('')||'<p class="hint">Nenhum feriado cadastrado.</p>';
}
async function load(){loaded=false;C.dates($('inicio').value,$('fim').value);message('Carregando ponto…');const current=loja();const [ev,raw,imp]=await Promise.all([
 all('ponto_eventos',q=>q.eq('loteria_id',current)),
 all('ponto_batidas',q=>q.eq('loteria_id',current).gte('instante',$('inicio').value+'T00:00:00').lte('instante',$('fim').value+'T23:59:59')),
 query(sb.from('ponto_importacoes').select('id,dispositivo,nome_arquivo,codigos,total_registros,criado_em').eq('loteria_id',current).order('criado_em',{ascending:false}))]);
 events=ev;punches=raw;imports=imp;loaded=true;render();renderImports();message('Dados carregados. Nenhum movimento automático no banco.');}
async function changeStore(){pending=null;$('arquivo').value='';$('previa').textContent='';$('confirmarImportacao').disabled=true;const id=loja();const links=await query(sb.from('usuarios_loterias').select('usuario_id,usuarios(id,nome,ativo)').eq('loteria_id',id));staff=[...new Map((links||[]).flatMap(v=>v.usuarios?Array.isArray(v.usuarios)?v.usuarios:[v.usuarios]:[]).map(u=>[u.id,u])).values()].sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR'));
 $('funcionario').innerHTML='<option value="">Selecione…</option>'+staff.map(u=>`<option value="${u.id}">${esc(u.nome)}${u.ativo?'':' (inativo)'}</option>`).join('');if(staff.length)$('funcionario').value=staff[0].id;await load();}
function modal(title,html,callback){$('modalTitle').textContent=title;$('modalBody').innerHTML=html;$('modalForm').onsubmit=e=>{e.preventDefault();if(busy)return;const values=Object.fromEntries(new FormData(e.currentTarget));run(async()=>{await callback(values);$('modal').close();await load();});};$('modal').showModal();}
const reason='<label>Motivo / observação<textarea name="motivo" required maxlength="500"></textarea></label>';
function edit(date){const d=days.find(d=>d.date===date);if(d.bank){message('Estorne o movimento desse dia no banco antes de tratar o ponto.',true);return;}
 modal('Tratar ponto — '+br(date),`<p>Original: ${esc(d.raw.map(p=>p.instante.slice(11)).join(' / ')||'Sem batidas')}</p><label>Situação<select name="situacao">${[['NORMAL','Trabalho normal'],['COMPENSACAO','Folga para compensar banco'],['ABONO','Ausência abonada'],['FERIAS','Férias'],['AFASTAMENTO','Afastamento'],['FOLGA','Folga sem débito'],['FERIADO','Feriado']].map(([v,n])=>`<option value="${v}" ${d.kind===v?'selected':''}>${n}</option>`).join('')}</select></label><label>Horários (HH:MM separados por espaço)<input name="horarios" value="${esc(d.times.join(' '))}" placeholder="09:00 12:00 13:00 18:00"></label><p class="hint">Para folga/abono, deixe os horários vazios. Uma compensação será enviada ao banco somente quando você selecionar o dia e confirmar.</p>${reason}`,async v=>{
 const times=v.horarios.trim()?v.horarios.trim().split(/[\s,;]+/):[];if(times.length>8)throw Error('Máximo de oito marcações.');times.forEach(t=>{if(!/^\d{2}:\d{2}$/.test(t)||C.minutes(t)>1439)throw Error('Horário inválido.');});
 if(v.situacao!=='NORMAL'&&times.length)throw Error('Remova os horários para registrar folga, feriado ou ausência.');
 await save([base('AJUSTE',date,v.motivo,{dados:{situacao:v.situacao,horarios:times}})]);
 });}
function original(date){if(!loaded)throw Error('Clique em Buscar para carregar o período atual.');const d=days.find(d=>d.date===date);$('modalTitle').textContent='Batidas originais — '+br(date);$('modalBody').innerHTML=`<p>Relógio → código → horário → indicação original</p>${d.raw.map(p=>`<p>${esc(p.dispositivo)} → ${esc(p.codigo)} → <strong>${esc(p.instante.slice(11))}</strong> → ${esc(p.tipo_original)}</p>`).join('')||'<p>Sem batidas vinculadas neste dia.</p>'}<p>Os ajustes não modificam esses registros.</p>`;$('modalForm').onsubmit=e=>{e.preventDefault();$('modal').close();};$('modal').showModal();}
function renderImports(){
 $('importacoes').innerHTML=imports.map(i=>`<div class="linkrow"><strong>${esc(i.nome_arquivo)}</strong><span>${esc(i.dispositivo)} · ${i.total_registros} registros · ${br(i.criado_em)}</span><button class="small secondary" data-download="${i.id}">Baixar original</button></div>`).join('')||'<p>Nenhum arquivo importado.</p>';
 const devices=[...new Set(imports.map(i=>i.dispositivo))];$('vinculos').innerHTML=devices.map(device=>{const maps=events.filter(e=>e.tipo==='VINCULO'&&e.dados.dispositivo===device);const codes=[...new Set([...maps.map(e=>e.dados.codigo),...imports.filter(i=>i.dispositivo===device).flatMap(i=>i.codigos||[]),...punches.filter(p=>p.dispositivo===device).map(p=>p.codigo),...(pending?.parsed.device===device?pending.parsed.people:[])])].sort();return `<h3>Relógio ${esc(device)}</h3>`+codes.map(code=>{
 const mapping=maps.filter(e=>e.dados.codigo===code&&e.data_referencia<=$('fim').value).sort((a,b)=>a.data_referencia.localeCompare(b.data_referencia)||a.criado_em.localeCompare(b.criado_em)).at(-1);
 return `<div class="linkrow"><strong>Código ${esc(code)}</strong><span>${esc(staff.find(s=>Number(s.id)===Number(mapping?.usuario_id))?.nome||'Não vinculado')}</span><button class="small secondary" data-map="${esc(device)}" data-code="${esc(code)}">Vincular / alterar vigência</button></div>`;}).join('');}).join('')||'<p>Importe o arquivo para identificar os códigos.</p>';
}
function link(device,code){modal('Vincular código '+code,`<p>Relógio: ${esc(device)}</p><label>Funcionário<select name="usuario" required><option value="">Selecione…</option>${staff.map(u=>`<option value="${u.id}">${esc(u.nome)}${u.ativo?'':' (inativo)'}</option>`).join('')}</select></label><label>Válido a partir de<input type="date" name="vigencia" value="${pending?.parsed.start||'2025-01-01'}" required></label>${reason}`,async v=>{
 // A validação por código, funcionário e vigência é feita atomicamente no banco.
 await save([base('VINCULO',v.vigencia,v.motivo,{usuario_id:Number(v.usuario),dados:{dispositivo:device,codigo:code}})]);
 });}
function bankSend(){if(!loaded)throw Error('Busque os dados antes de enviar.');const selected=[...document.querySelectorAll('.diaCheck:checked')].map(x=>days.find(d=>d.date===x.value));if(!selected.length)throw Error('Selecione dias com diferença apurada.');
 modal('Confirmar envio ao banco',`<p>${selected.length} dias de ${esc(person().nome)}.</p><p>Créditos: <strong>${C.hm(selected.reduce((s,d)=>s+Math.max(0,d.delta),0))}</strong> · Débitos: <strong>${C.hm(selected.reduce((s,d)=>s+Math.min(0,d.delta),0))}</strong></p><p>Movimento líquido: <strong>${C.hm(selected.reduce((s,d)=>s+d.delta,0))}</strong></p>${reason}`,async v=>await save(selected.map(d=>base('BANCO',d.date,v.motivo,{minutos:d.delta,origem:'dia:'+d.date,dados:{horarios:d.times,situacao:d.kind,jornada:rule(d.date),partes:d.parts,trabalhadas:d.worked}}))));}
function pay(){if(!user())throw Error('Selecione funcionário.');const date=$('fim').value;modal('Registrar pagamento de horas',`<p>Funcionário: ${esc(person().nome)}. O saldo negativo anterior já está compensado no saldo disponível.</p><label>Data efetiva do pagamento<input type="date" name="data" required value="${date}"></label><label>Competência das horas<input type="month" name="competencia" required value="${date.slice(0,7)}"></label><label>Horas pagas (HH:MM)<input name="horas" required value="${C.hm(Math.max(0,C.balance(employeeEvents(),date)))}" pattern="[0-9]{2,3}:[0-5][0-9]"></label>${reason}`,async v=>{const m=C.minutes(v.horas);if(m<=0)throw Error('Informe quantidade positiva.');if(v.data>today())throw Error('Pagamento não pode ter data futura.');await save([base('PAGAMENTO',v.data,v.motivo,{competencia:v.competencia+'-01',minutos:-m,dados:{pago_em:v.data}})]);});}
function manual(){if(!user())throw Error('Selecione funcionário.');modal('Movimento manual no banco',`<label>Data efetiva<input type="date" name="data" required value="${$('fim').value}"></label><label>Movimento<select name="sinal"><option value="1">Crédito</option><option value="-1">Débito</option></select></label><label>Horas (HH:MM)<input name="horas" required placeholder="04:00" pattern="[0-9]{2,3}:[0-5][0-9]"></label><p class="hint">Um único movimento ativo por dia. Para folga compensatória, prefira tratar o dia e enviá-lo ao banco.</p>${reason}`,async v=>{const m=C.minutes(v.horas)*Number(v.sinal);if(!m)throw Error('Informe horas.');await save([base('BANCO',v.data,v.motivo,{minutos:m,origem:'dia:'+v.data,dados:{manual:true}})]);});}
function reverse(id){const e=events.find(e=>e.id===id);modal('Estornar movimento',`<p>${br(e.data_referencia)} · ${esc(e.tipo)} · ${C.hm(e.minutos)}. O estorno preserva o lançamento original.</p>${reason}`,async v=>await save([base('ESTORNO',e.data_referencia,v.motivo,{minutos:-e.minutos,estorno_de:id})]));}
function restore(){if(!user())throw Error('Selecione funcionário.');const active=employeeEvents().filter(e=>e.tipo==='BANCO'&&e.data_referencia>=$('inicio').value&&e.data_referencia<=$('fim').value&&!events.some(r=>r.estorno_de===e.id));const payments=employeeEvents().filter(e=>e.tipo==='PAGAMENTO'&&e.competencia>=month($('inicio').value)&&e.competencia<=month($('fim').value)&&!events.some(r=>r.estorno_de===e.id));
 modal('Restaurar ponto do período',`<p>${esc(person().nome)} · ${br($('inicio').value)} a ${br($('fim').value)}.</p><p>Os ajustes serão desativados e <strong>${active.length} movimentos diários serão estornados</strong>. As batidas, jornadas, vínculos e feriados serão preservados.</p>${payments.length?'<p class="warning">Há pagamentos associados a essas competências. Eles permanecem registrados; se necessário, estorne-os separadamente. A restauração pode deixar o banco negativo.</p>':''}${reason}`,async v=>await query(sb.rpc('ponto_restaurar',{p_loja:loja(),p_usuario:user(),p_inicio:$('inicio').value,p_fim:$('fim').value,p_motivo:v.motivo})));
}
function printReport(){if(!user()||!loaded)throw Error('Selecione funcionário e busque o período.');const ev=employeeEvents();const content={loja:ctx.lojasPermitidas.find(l=>Number(l.loteria_id)===loja()).loteria_nome,nome:person().nome,inicio:$('inicio').value,fim:$('fim').value,emitido:new Date().toISOString(),dias:days.map(d=>({data:d.date,horarios:d.times,situacao:d.status,ajustado:d.adjusted,motivo:d.reason,trabalhadas:d.worked,previstas:d.expected,diferenca:d.delta,banco:d.bank?.minutos??0})),saldo:C.balance(ev,$('fim').value),movimentos:ev.filter(e=>['BANCO','PAGAMENTO','ESTORNO'].includes(e.tipo)&&e.data_referencia>=$('inicio').value&&e.data_referencia<=$('fim').value)};
 const win=window.open('','_blank');if(!win)throw Error('Permita a abertura da janela do relatório.');
 const rows=content.dias.map(d=>`<tr><td>${br(d.data)}</td><td>${esc(d.horarios.join(' / ')||d.situacao)}</td><td>${d.trabalhadas===null?'—':C.hm(d.trabalhadas)}</td><td>${C.hm(d.previstas)}</td><td>${d.diferenca===null?'Pendente':C.hm(d.diferenca)}</td><td>${C.hm(d.banco)}</td><td>${esc(d.ajustado?'Ajustado: '+d.motivo:d.motivo)}</td></tr>`).join('');
 win.document.write(`<!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><title>Folha de Ponto - ${esc(content.nome)} - ${content.inicio.slice(0,7)}</title><style>@page{size:A4 portrait;margin:12mm}body{font:10px Arial;color:#111}h1{font-size:19px;padding-bottom:10px;border-bottom:3px solid #226348}h2{font-size:13px;color:#226348}th{background:#edf3ef}tbody tr:nth-child(even){background:#f7f9f8}table{width:100%;border-collapse:collapse}td,th{padding:5px;border:1px solid #ccc;text-align:left}thead{display:table-header-group}tr{break-inside:avoid}.summary{margin:15px 0}.sign{break-inside:avoid;margin-top:25px;display:flex;justify-content:space-between;gap:25px}.sign div{border-top:1px solid #333;padding-top:6px;width:46%}button{padding:10px;margin:10px 0}@media print{button{display:none}}.warn{font-weight:bold}</style></head><body><button onclick="window.print()">Imprimir / Salvar como PDF</button><h1>Folha de Ponto — ${esc(content.loja)}</h1><p><strong>Funcionário:</strong> ${esc(content.nome)} · ID SISLOT: ${user()}</p><p>Período: ${br(content.inicio)} a ${br(content.fim)} · Emitido em ${new Date(content.emitido).toLocaleString('pt-BR',{timeZone:'America/Sao_Paulo'})}</p>${content.dias.some(d=>d.diferenca===null)?'<p class="warn">RELATÓRIO COM PENDÊNCIAS — conferir dias incompletos antes da assinatura.</p>':''}<table><thead><tr><th>Data</th><th>Marcações</th><th>Trabalho real</th><th>Previsto</th><th>Diferença apurada</th><th>Enviado ao BH</th><th>Observações</th></tr></thead><tbody>${rows}</tbody></table><div class="summary"><strong>Trabalho real: ${C.hm(content.dias.reduce((s,d)=>s+(d.trabalhadas||0),0))} · Diferença apurada: ${C.hm(content.dias.reduce((s,d)=>s+(d.diferenca||0),0))} · Saldo BH em ${br(content.fim)}: ${C.hm(content.saldo)}</strong><p>Diferença apurada não representa pagamento nem envio automático ao banco.</p></div><h2>Movimentos do banco no período</h2><table><thead><tr><th>Data efetiva</th><th>Competência</th><th>Tipo</th><th>Horas</th><th>Motivo</th></tr></thead><tbody>${content.movimentos.sort((a,b)=>a.data_referencia.localeCompare(b.data_referencia)||a.criado_em.localeCompare(b.criado_em)).map(e=>`<tr><td>${br(e.data_referencia)}</td><td>${e.competencia.slice(0,7)}</td><td>${e.tipo}</td><td>${C.hm(e.minutos)}</td><td>${esc(e.motivo)}</td></tr>`).join('')||'<tr><td colspan="5">Sem movimentos.</td></tr>'}</tbody></table><p>Jornada no início do período: ${esc(rule(content.inicio)?.weekday.join(' / ')||'Não cadastrada')} · Sábado: ${esc(rule(content.inicio)?.saturday.join(' / ')||'Não cadastrado')}. Alterações de jornada possuem vigência.</p><div class="sign"><div>${esc(content.nome)} — Assinatura do funcionário<br>Data: ____/____/________</div><div>Responsável pela conferência<br>Data: ____/____/________</div></div></body></html>`);win.document.close();
}
async function preview(){const file=$('arquivo').files[0];if(!file)return;if(file.size>20*1024*1024)throw Error('Limite: 20 MB.');const bytes=await file.arrayBuffer();const parsed=C.parse(C.decode(bytes));let binary='';for(const b of new Uint8Array(bytes))binary+=String.fromCharCode(b);pending={file,parsed,base64:btoa(binary),loja:loja()};$('previa').innerHTML=`<p><strong>${esc(parsed.device)}</strong> · ${parsed.rows.length} batidas · ${br(parsed.start)} a ${br(parsed.end)}.</p><p>Códigos: ${esc(parsed.people.join(', '))}. Confirme o vínculo de cada código depois de importar.</p>`;$('confirmarImportacao').disabled=false;}
async function initialize(){try{
 ctx=await window.SISLOT_SECURITY.protegerPagina('ponto');if(!ctx)return;const t=today();$('inicio').value=month(t);$('fim').value=t;$('vigencia').value=t;
 $('loja').innerHTML=ctx.lojasPermitidas.map(l=>`<option value="${l.loteria_id}">${esc(l.loteria_nome)}</option>`).join('');if(ctx.lojaInicial)$('loja').value=ctx.lojaInicial.loteria_id;
 if(!ctx.lojasPermitidas.length)throw Error('Nenhuma loja autorizada.');await changeStore();
 }catch(e){message('Não foi possível carregar: '+e.message+'. Confira se ponto-instalacao.sql foi instalado.',true);}}
$('buscar').onclick=()=>run(load);$('loja').onchange=()=>run(changeStore);$('funcionario').onchange=()=>run(load);
['inicio','fim'].forEach(id=>$(id).onchange=()=>{loaded=false;updateSelection();message('Período alterado. Clique em Buscar antes de operar.');});
$('arquivo').onchange=()=>{pending=null;$('confirmarImportacao').disabled=true;preview().catch(e=>message(e.message,true));};
$('confirmarImportacao').onclick=()=>run(async()=>{if(!pending||pending.loja!==loja())throw Error('Selecione novamente o arquivo.');const result=await query(sb.rpc('ponto_importar',{p_loja:loja(),p_dispositivo:pending.parsed.device,p_nome:pending.file.name,p_base64:pending.base64,p_batidas:pending.parsed.rows}));await load();message(`Importação concluída: ${result.novas} batidas novas; ${result.repetidas} repetidas. Confira os vínculos.`);});
$('todos').onchange=()=>{document.querySelectorAll('.diaCheck:not(:disabled)').forEach(c=>{if(!c.closest('tr').hidden)c.checked=$('todos').checked;});updateSelection();};
$('dias').addEventListener('change',updateSelection);$('filtroDias').onchange=filterDays;
$('mesAnterior').onclick=()=>run(()=>selectMonth(-1));$('mesSeguinte').onclick=()=>run(()=>selectMonth(1));$('mesAtual').onclick=()=>run(()=>selectMonth(0,true));
function guarded(fn){return ()=>{try{if(!loaded)throw Error('Clique em Buscar para carregar o período atual.');fn();}catch(e){message(e.message,true);}};}
$('enviar').onclick=guarded(bankSend);$('pagar').onclick=guarded(pay);$('manual').onclick=guarded(manual);$('restaurar').onclick=guarded(restore);$('relatorio').onclick=guarded(printReport);$('liquidados').onchange=renderBank;$('cancelar').onclick=()=>$('modal').close();
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(s=>s.hidden=s.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-current',x===b?'page':'false');});});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||busy)return;
 try{if(b.dataset.edit)guarded(()=>edit(b.dataset.edit))();if(b.dataset.original)original(b.dataset.original);if(b.dataset.reverse)guarded(()=>reverse(b.dataset.reverse))();if(b.dataset.map)link(b.dataset.map,b.dataset.code);
 if(b.dataset.download)run(async()=>{const i=await query(sb.from('ponto_importacoes').select('arquivo_base64,nome_arquivo').eq('id',b.dataset.download).single());const bytes=Uint8Array.from(atob(i.arquivo_base64),x=>x.charCodeAt(0));const url=URL.createObjectURL(new Blob([bytes],{type:'application/octet-stream'}));const a=document.createElement('a');a.href=url;a.download=i.nome_arquivo;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 if(b.dataset.holiday){const h=events.find(x=>x.id===b.dataset.holiday);modal('Desativar feriado',`<p>${br(h.data_referencia)} — ${esc(h.dados.nome)}. O cadastro anterior permanecerá no histórico.</p>${reason}`,async v=>await save([base('FERIADO',h.data_referencia,v.motivo,{usuario_id:null,dados:{nome:h.dados.nome,ativo:false}})]));}
 }catch(err){message(err.message,true);}});
$('jornadaForm').onsubmit=e=>{e.preventDefault();run(async()=>{if(!user())throw Error('Selecione funcionário.');const date=$('vigencia').value;const w=['j1','j2','j3','j4'].map(id=>$(id).value),s=[$('s1').value,$('s2').value];if(w.some((v,i)=>i&&v<=w[i-1])||s[1]<=s[0])throw Error('Horários devem estar em ordem crescente.');if(employeeEvents().some(e=>e.tipo==='BANCO'&&e.data_referencia>=date&&!events.some(r=>r.estorno_de===e.id)))throw Error('Estorne os dias enviados ao banco após a vigência antes de alterar a jornada.');await save([base('JORNADA',date,'Cadastro de jornada com vigência',{dados:{weekday:w,saturday:s,late:Number($('atraso').value),extra:Number($('he').value),early:Number($('antecipada').value),interval:$('intervalo').value,threshold:$('limiar').value,extraPercent:Number($('percentual').value)}})]);await load();});};
$('feriadoForm').onsubmit=e=>{e.preventDefault();run(async()=>{await save([base('FERIADO',$('feriadoData').value,'Cadastro de feriado',{usuario_id:null,dados:{nome:$('feriadoNome').value.trim(),ativo:true}})]);await load();});};
initialize();
})();
